### ISSUE TITLE
Question: what does `ResolverFor` type look like?

### ISSUE THREAD

**Issue by acro5piano** [dotansimha/graphql-typed-ast#2]
Hi, thank you for creating awesome repository.
I have a question about README: what does `ResolverFor` type look like? I'm curious how to use `ParseGraphQLLexer` but couldn't find any definitions of `ResolverFor`. Thanks!

**Comment by dotansimha** [comment]
Hi @acro5piano ! 
It's an experiment we are working on, to create TypeScript resolvers signature based on SDL (with TS 4.1).
It has a few issues at the moment:
* Then need to generate the return types of resolvers to have strict validations.
* The need to build the base types separately since we need to allow some level of circular links between types.
* Performance limitations with TS 4.1 - to parse GraphQL multiline string, it requires to do multiple trimming process, which leads to the limit of TS after about 3-4 GraphQL types. 

We are still working and experimenting, I guess code-generators will stay here for a bit longer ;)

**Comment by acro5piano** [comment]
Okay thanks! I'm looking forward to your work.

I'm the author of typed-graphqlify and graphql-typed-ast inspires me a lot.

https://github.com/acro5piano/typed-graphqlify

**Comment by dotansimha** [comment]
Awesome! I think we'll try to improve that soon, it could be great to collaborate!!

**Comment by acro5piano** [comment]
> Performance limitations with TS 4.1 - to parse GraphQL multiline string, it requires to do multiple trimming process, which leads to the limit of TS after about 3-4 GraphQL types.

I've struggled this for 2 days and the performance limitation is significant. Sometimes it spoils type definition completely.

By the way, how do you treat the AST which has `next` attribute? You might parse GQL string then manipulate it with `ResolverFor`. I thought that part is the key of handling deep object.

My current approach is to parse string directly.

``` typescript
type Parse<T extends string> =
  T extends `${Whitespace}${infer Next}` ? Parse<Next> :
  T extends `${Operation} {${infer Next}` ? Parse<Next> :
  T extends `${Letter}${infer Next}` ?
    AfterName<Next> extends `{${infer _}}${infer AfterBracket}` ?
      { [k in ReadName<T>]: Parse<GetBracketInner<Trim<AfterName<Next>>>> } & Parse<AfterBracket> :    // When the word opens "{"
      { [k in ReadName<T>]: /* TODO: */ string } & Parse<`${AfterName<Next>}`> :
  T extends `}${infer Next}` ? Parse<Next> :
  T extends `` ? {} :
  never

const query = `
  query {
    hello
    posts {
      id
      title
    }
    users {
      id
      gender
    }
  }
`

type Actual = ParseGql<typeof query>

type Expected = {
  hello: string
  posts: {
    id: string
    title: string
  }
  users: {
    id: string
    gender: string
  }
}
```

**Comment by acro5piano** [comment]
I must learn Lexer parser & ast. Sorry for bothering you!

**Comment by dotansimha** [comment]
All good, don't worry :) 
I was trying to parse directly, but it seems like it's limited. Also dealing with `next:` - the limitation comes from the fact that most graphql definitions are multiline strings, and the fact the whitespaces are allowed. 
Removing those whitespaces eventually causes performance issues due to the fact that it uses greedy lookup.

I think the only way to get good results with that, is to have intrinsic type in TS that does Regex. This way we'll be able to clear whitespace without creating a greedy lookup, and then we can focus on parsing the SDL to AST (or, anything else). 
TS 4.1 already have intrinsic types such as Uppercase, I would imagine that having one for Regex could solve most of the issues.

**Comment by acro5piano** [comment]
@dotansimha Thank you for sharing your thoughts. I understand what is going on. I'll learn Lexer/AST to prepare the TS's intrinsic type for Regex!
